本项目的目标是构建 [[http://open-advice.org/][Open Advice]] 这本书的中文翻译版本。同时，设立本项目也是为了能够为”开源课程@zjut“的同学提供一
个深入接触开源的机会，让同学们亲身参与开源的组织和生产方式，体验开源的苦与乐。所做的工作和原书一样，遵循
CC-BY-SA 许可证。
* 关于 Open Advice
“站在巨人的肩膀上才能看得更远”，42 位开源社区杰出贡献者在 Open Advice 一书中讲述他们各自在社区不同领域的经验。

与其他以往偏重代码的开源社区类书籍不同，本书覆盖的角度十分广泛，包括：
- 概念、创新和研究
- 招募和督导
- 基础构架和代码编写
- 质量保证和支持文档
- 翻译、用户可用性和艺术设计
- 社区管理
- 打包
- 市场宣传，会议组织
- 商业模式、法律和规范。

推荐该书给：

1. 不满足通俗媒体报道，深入了解开源社区如何运作的人。
2. 希望加入开源社区做贡献，但心有顾虑的人。
3. 愿前辈们的经验帮助您更快的了解并融入开源社区。

关于该书的作者、下载或购买等信息请登录主页 http://open-advice.org

* 关于翻译方式
原书采用 \LaTeX 排版，并提供所有源文件的下载。目前本项目的库中已经包含了原书（2012年10月19日）的源。

我们主要需要翻译的文件就是各个 *子目录中的 .tex 文件* 。可以采用”逐段翻译“的方式：
1. 用文本编辑器打开某个子目录中某个 .tex 文件。你会看到大段的英文文字和一些以\打头的单词（后面通常还有大括号），
   后者是 \LaTeX 的命令，不要翻译，你只需要翻译前者。如果你不能确定到底哪些是命令哪些是内容，也可以对照本书的电
   子版本，应该是一目了然的；而且这个过程也可以帮助你学习 \LaTeX 排版。
2. 你可以在该目录中为该文件建立一个对应的中文翻译文件。建议对应的中文翻译文件采用 zh_CN- 作为前缀。比如，如果原
   文件名字为 AustinAppel.tex ，那么可以建立一个 zh_CN-AustinAppel.tex 文件。所有的 \LaTeX 命令照搬，然后对内容
   进行逐段翻译。
3. 翻译完一段（或者一个比较完整的部分）就及时将内容提交，以便其他人员对你的翻译进行阅读或者修改。需要注意的是，
   翻译的内容每一行尽量保持和原文内容对应，便于之后别人对照以及对翻译进行修改完善。


我们需要注意的是，这个工作的成果是共享出去的。换句话说，它的质量决定了它的效用。因此千万不要用什么软件进行自动
翻译！！！

** 如何参与开源项目?
[github的多人协作？how to 贡献代码？](https://github.com/suziewong/Open-Advice_Chinese-Edition/wiki/github%E7%9A%84%E5%A4%9A%E4%BA%BA%E5%8D%8F%E4%BD%9C%EF%BC%9Fhow-to-%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81%EF%BC%9F)




